# Generated by Django 6.0.5 on 2026-09-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi bi-folder', help_text='Classe Bootstrap Icons, ex: bi bi-truck', max_length=100),
        ),
    ]
